from __future__ import annotations
from typing import Optional
from .models import ProjectSpec
from .agent_blueprint import build_spec, apply_instruction
from .factory_renderer import render_file

def generate_file(path: str, spec: ProjectSpec, use_ai: bool = True, previous_errors: Optional[list[str]] = None) -> str:
    rendered = render_file(path, spec)
    if rendered is not None:
        return rendered
    if path == "backend/requirements.txt":
        return "fastapi==0.111.0\nuvicorn[standard]==0.30.1\npydantic==2.7.4\n"
    if path == "frontend/package.json":
        return '{"scripts":{"dev":"vite --host 0.0.0.0","build":"vite build","preview":"vite preview"},"dependencies":{"@vitejs/plugin-react":"latest","vite":"latest","react":"latest","react-dom":"latest"},"devDependencies":{}}'
    if path == "frontend/index.html":
        return '<div id="root"></div><script type="module" src="/src/main.jsx"></script>'
    if path == "frontend/src/main.jsx":
        return "import React from 'react';\nimport { createRoot } from 'react-dom/client';\nimport App from './App.jsx';\nimport './styles.css';\ncreateRoot(document.getElementById('root')).render(<App />);\n"
    if path == "README.md":
        return f"# {spec.app_name}\n\n{spec.goal}\n\nGenerated by Codem8s agent blueprint engine.\n"
    return f"# Generated file for {path}\n"
