from __future__ import annotations

import ast
import json
import re
from pathlib import PurePosixPath
from typing import Dict, List, Tuple

BANNED_PHRASES = [
    "TODO", "NotImplementedError", "implementation here", "your code here",
    "example only", "dummy data", "lorem ipsum", "pass #",
    "welcome to your", "comprehensive tool for managing", "generated by codem8s agent blueprint engine",
]

REQUIRED_EXPORTS = {
    "backend/main.py": ["app"],
    "backend/generator.py": ["build_spec", "generate_file"],
    "backend/validator.py": ["validate_file", "detect_placeholders"],
    "backend/settings.py": ["load_settings", "save_settings", "settings_status"],
}

CODE_EXTENSIONS = (".js", ".jsx", ".ts", ".tsx", ".py", ".css")
JS_EXTENSIONS = (".js", ".jsx", ".ts", ".tsx")
ASSET_EXTENSIONS = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico", ".svg")


def safe_path(path: str) -> bool:
    p = PurePosixPath(path)
    return not path.startswith("/") and ".." not in p.parts and len(path.strip()) > 0


def detect_placeholders(content: str) -> List[str]:
    found: List[str] = []
    lowered = content.lower()
    for phrase in BANNED_PHRASES:
        if phrase.lower() in lowered:
            found.append(phrase)
    if re.search(r"(?i)(placeholder|empty|fake|todo|temporary)\s+stub|stub\s+(component|file|implementation|function|screen|placeholder)", content):
        found.append("stub placeholder")
    return found


def detect_placeholder_only_file(path: str, content: str) -> List[str]:
    errors: List[str] = []
    stripped = content.strip()
    lines = [line.strip() for line in stripped.splitlines() if line.strip()]

    if path.endswith(ASSET_EXTENSIONS):
        if not stripped:
            errors.append("asset file is empty")
        if re.fullmatch(r"(?s)\s*(#|//)\s*[^\n]*\.(png|jpg|jpeg|gif|webp|ico|svg)\s*", stripped, re.I):
            errors.append("fake asset file; binary/image asset was generated as a text comment")
        if path.endswith((".png", ".jpg", ".jpeg", ".gif", ".webp", ".ico")) and not stripped.startswith(("data:image/", "BASE64:", "iVBOR", "/9j/", "R0lGOD")):
            errors.append("binary asset must be base64/data-url content or generated as a real code-rendered asset")
        return errors

    if not path.endswith(CODE_EXTENSIONS):
        return errors
    if not lines:
        errors.append("file is empty")
        return errors
    if len(lines) <= 3 and all(re.match(r"^(#|//|/\*|\*)\s*(File|Path)\s*:", line, re.I) or line in {"*/"} for line in lines):
        errors.append("placeholder-only file marker; generated file contains no implementation")
    if re.fullmatch(r"(?s)\s*(#|//)\s*File:\s*[^\n]+\s*", content):
        errors.append("placeholder-only file marker; generated file contains no implementation")
    if path.endswith((".ts", ".tsx", ".js", ".jsx")):
        code_without_comments = re.sub(r"(?m)^\s*(//|#).*$", "", stripped)
        code_without_comments = re.sub(r"/\*.*?\*/", "", code_without_comments, flags=re.S).strip()
        if len(code_without_comments) < 25 and re.search(r"(File|Path)\s*:", stripped, re.I):
            errors.append("code file is only a filename comment")
    return errors


def detect_recovered_fallback(path: str, content: str) -> List[str]:
    errors: List[str] = []
    if not path.endswith(JS_EXTENSIONS):
        return errors
    low = content.lower()
    if "data-generated-fallback" in content or "Recovered module" in content or "AI builder failed or returned weak code" in content:
        if path.endswith(("App.tsx", "App.jsx", "GameScreen.tsx", "GameScreen.jsx", "CanvasMap.tsx", "CanvasMap.jsx")):
            errors.append(f"{path}: recovered fallback is not acceptable for core rendered app/game files")
        elif len(content.strip()) < 900:
            errors.append(f"{path}: recovered fallback is too shallow to count as a finished implementation")
    if "reason: 'AI builder failed" in content or 'reason: "AI builder failed' in content:
        errors.append(f"{path}: fallback data module accepted instead of real implementation")
    return errors


def detect_markdown_or_bad_prefix(path: str, content: str) -> List[str]:
    errors: List[str] = []
    if not path.endswith(CODE_EXTENSIONS):
        return errors
    stripped = content.lstrip("\ufeff\n\r\t ")
    if stripped.startswith("```"):
        errors.append("code file starts with markdown fence ```")
    elif stripped.startswith("`"):
        errors.append("code file starts with stray backtick")
    if "```" in stripped:
        errors.append("code file contains markdown fence ```")
    return errors


def validate_python(content: str) -> List[str]:
    try:
        ast.parse(content)
        return []
    except SyntaxError as exc:
        return [f"SyntaxError line {exc.lineno}: {exc.msg}"]


def exported_names(content: str) -> set[str]:
    names: set[str] = set()
    try:
        tree = ast.parse(content)
    except SyntaxError:
        return names
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ClassDef := ast.ClassDef)):
            names.add(node.name)
        elif isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name):
                    names.add(target.id)
    return names


def js_exports(content: str) -> tuple[set[str], bool]:
    named: set[str] = set()
    has_default = bool(re.search(r"\bexport\s+default\b", content))
    for pattern in [
        r"\bexport\s+function\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+class\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+const\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+let\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+var\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+type\s+([A-Za-z_$][\w$]*)",
        r"\bexport\s+interface\s+([A-Za-z_$][\w$]*)",
    ]:
        named.update(re.findall(pattern, content))
    for group in re.findall(r"\bexport\s*\{([^}]+)\}", content, re.S):
        for part in group.split(","):
            token = part.strip()
            if not token:
                continue
            if " as " in token:
                token = token.split(" as ")[-1].strip()
            token = re.sub(r"[^A-Za-z0-9_$].*$", "", token)
            if token:
                named.add(token)
    return named, has_default


def parse_package_dependencies(files: Dict[str, str]) -> set[str]:
    deps: set[str] = set()
    raw = files.get("frontend/package.json") or files.get("package.json")
    if not raw:
        return deps
    try:
        data = json.loads(raw)
        for key in ["dependencies", "devDependencies"]:
            deps.update((data.get(key) or {}).keys())
    except Exception:
        pass
    return deps


def resolve_import_path(from_path: str, import_path: str, files: Dict[str, str]) -> str | None:
    if not import_path.startswith("."):
        return None
    base = PurePosixPath(from_path).parent
    raw = str((base / import_path).as_posix())
    candidates = [raw, raw + ".js", raw + ".jsx", raw + ".ts", raw + ".tsx", raw + ".css", raw + "/index.js", raw + "/index.jsx", raw + "/index.ts", raw + "/index.tsx"]
    for candidate in candidates:
        clean = str(PurePosixPath(candidate))
        if clean in files:
            return clean
    return None


def iter_imports(content: str) -> list[tuple[str, str, str]]:
    imports: list[tuple[str, str, str]] = []
    for names_text, import_path in re.findall(r"import\s*\{([^}]+)\}\s*from\s*['\"]([^'\"]+)['\"]", content):
        imports.append(("named", names_text, import_path))
    for default_name, import_path in re.findall(r"import\s+([A-Za-z_$][\w$]*)\s+from\s*['\"]([^'\"]+)['\"]", content):
        imports.append(("default", default_name, import_path))
    for import_path in re.findall(r"import\s*['\"]([^'\"]+)['\"]", content):
        imports.append(("sideeffect", "", import_path))
    return imports


def validate_js_import_exports(files: Dict[str, str]) -> List[str]:
    errors: List[str] = []
    export_cache: dict[str, tuple[set[str], bool]] = {}
    deps = parse_package_dependencies(files)
    allowed_bare = {"react", "react-dom", "react-dom/client", "vite", "@vitejs/plugin-react", "typescript", "react-router-dom", "@types/react", "@types/react-dom"} | deps
    for path, content in files.items():
        if path.endswith(JS_EXTENSIONS):
            export_cache[path] = js_exports(content)

    for path, content in files.items():
        if not path.endswith(JS_EXTENSIONS):
            continue
        if "require(" in content:
            errors.append(f"{path}: uses CommonJS require(); Vite app files must use ES imports")
        for bare in re.findall(r"from\s*['\"]([^.'\"][^'\"]*)['\"]", content):
            if bare not in allowed_bare and not bare.startswith("@vitejs/"):
                errors.append(f"{path}: imports package {bare}, but it is not in frontend/package.json")

        for kind, names_text, import_path in iter_imports(content):
            if import_path.startswith("."):
                target = resolve_import_path(path, import_path, files)
                if not target:
                    errors.append(f"{path}: imports missing local file {import_path}")
                    continue
                if target.endswith(".css"):
                    continue
                if target not in export_cache:
                    continue
                exported, has_default = export_cache[target]
                if kind == "named":
                    for raw_name in names_text.split(","):
                        name = raw_name.strip()
                        if not name:
                            continue
                        if " as " in name:
                            name = name.split(" as ")[0].strip()
                        if name not in exported:
                            errors.append(f"{path}: imports named export {name} from {target}, but {target} exports {sorted(exported) or 'no named exports'}")
                elif kind == "default" and not has_default:
                    errors.append(f"{path}: imports default {names_text} from {target}, but {target} has no default export")
    return errors


def validate_product_depth(files: Dict[str, str]) -> List[str]:
    errors: List[str] = []
    app = files.get("frontend/src/App.jsx", "") or files.get("frontend/src/App.tsx", "") or files.get("frontend/App.tsx", "")
    dashboard = files.get("frontend/src/components/Dashboard.jsx", "")
    sample = files.get("frontend/src/data/sampleData.js", "")
    styles = files.get("frontend/src/styles.css", "") or files.get("frontend/src/styles/global.css", "")

    if app:
        low = app.lower()
        if "welcome" in low and "button" not in low and "canvas" not in low:
            errors.append("frontend app shell: generic welcome-only screen is not acceptable")
        jsx_tags = len(re.findall(r"<\w+", app))
        app_sections = sum(term in low for term in ["dashboard", "activity", "task", "project", "metric", "kpi", "table", "status", "filter", "search", "chart", "timeline", "canvas", "toolbar", "resource", "map", "route", "vehicle"])
        if jsx_tags < 8 or app_sections < 3:
            errors.append("frontend app shell is too shallow; must render a rich product/game UI")
    if dashboard:
        low = dashboard.lower()
        dashboard_sections = sum(term in low for term in ["kpi", "metric", "activity", "status", "chart", "table", "recent", "priority", "progress", "timeline"])
        if dashboard_sections < 5 or len(dashboard.strip()) < 1200:
            errors.append("frontend/src/components/Dashboard.jsx: dashboard is too shallow; needs KPIs, activity, status breakdowns, and lists")
    if sample:
        low = sample.lower()
        real_data_signals = sum(term in low for term in ["priority", "status", "date", "comment", "activity", "team", "due", "progress", "owner", "note"])
        if real_data_signals < 6 or len(sample.strip()) < 2000:
            errors.append("frontend/src/data/sampleData.js: sample data is too thin for product-depth generation")
    if styles:
        low = styles.lower()
        design_signals = sum(term in low for term in ["linear-gradient", "grid", "box-shadow", "border-radius", "sidebar", "badge", "card", "kpi", "media", "responsive", "canvas", "toolbar"])
        if design_signals < 6:
            errors.append("frontend styles: design system is too basic")
    return errors


def validate_file(path: str, content: str, spec_files: Dict[str, str]) -> Tuple[bool, List[str]]:
    errors: List[str] = []
    if not safe_path(path):
        errors.append("unsafe path")
    if path not in spec_files:
        errors.append("file is not in locked manifest")
    if len(content.strip()) < 20:
        errors.append("file is too small to be useful")
    errors.extend(detect_placeholder_only_file(path, content))
    errors.extend(detect_markdown_or_bad_prefix(path, content))
    errors.extend(detect_recovered_fallback(path, content))
    if not path.endswith("validator.py"):
        for phrase in detect_placeholders(content):
            errors.append(f"banned placeholder phrase: {phrase}")
    if path.endswith(".py"):
        errors.extend(validate_python(content))
        required = REQUIRED_EXPORTS.get(path, [])
        names = exported_names(content)
        for name in required:
            if name not in names:
                errors.append(f"missing required export/name: {name}")
    return len(errors) == 0, errors
